
### REST extension to manual test the server
GET http://localhost:3001/api/sessions/current HTTP/1.1

### 

POST http://localhost:3001/api/sessions/ HTTP/1.1
content-type: application/json

{
    "username": "sample",
    "password": "whatever"
}


###
GET http://localhost:3001/api/services

###
POST http://localhost:3001/api/ticket 
content-type: application/json

{
    "serviceType": "shipping",
    "ts":"23-10-2023 15:00:00",
    "status":"pending"
}