
### REST extension to manual test the server
GET http://localhost:3001/api/sessions/current HTTP/1.1

### 

POST http://localhost:3001/api/sessions/ HTTP/1.1
content-type: application/json

{
    "username": "MRossi",
    "password": "password3"
}


###
GET http://localhost:3001/api/services

###
GET http://localhost:3001/api/nextcustomer/2

###
PUT http://localhost:3001/api/assignticket/0
content-type: application/json

{
    "counterId":2,
    "employeeId":5
}

###
PUT http://localhost:3001/api/closeticket/0

###
POST http://localhost:3001/api/ticket 
content-type: application/json

{
    "serviceType": "shipping",
    "ts":"23-10-2023 15:00:00",
    "status":"pending"
}

###
DELETE http://localhost:3001/api/tickets/30